# Generated by Django 4.2.15 on 2024-11-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('idHash', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='Hà Nội', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='user@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='numberPhone',
            field=models.CharField(default='0123456789', max_length=255),
        ),
    ]
