# Generated by Django 4.2.15 on 2024-11-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hash_userinfo_address_userinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='id_qr',
            field=models.TextField(default='QR123', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id_qr',
            field=models.TextField(default='QR123', max_length=255),
        ),
    ]
